
name: black

on: [push, pull_request]


jobs:
  black:
    name: Style Check with Black&iSort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install black==20.8b1 isort"
        name: Install black and isort
      - run: "make reformat"
        name: Format
        continue-on-error: true
      - name Commit changes
        run: |
           git config --local committer.email "noreply@github.com"
           git config --local committer.name "GitHub"
           git config --local author.email "${{ github.actor }}@users.noreply.github.com"
           git config --local author.name "{{ github.actor }}"
           git add .
           git commit -m "Style Reformatting"
           git push


  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle git+https://gitlab.com/pycqa/flake8@3.7.9#egg=flake8"
        name: Install Flake8
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
        name: Flake8 Linting
