name: Style formatting

on: [push, pull_request]

jobs:
  mypy:
    name: Style check with Black and iSort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "python -m pip install black==19.10b0 isort==5.2.2"
        name: Install dependencies
      - run: "make stylediff"
        name: Run Style Checks

  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "python -m pip install git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle git+https://gitlab.com/pycqa/flake8@3.7.9#egg=flake8"
        name: Install Flake8
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
        name: Flake8 Linting